// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20190204134916_treca")]
    partial class treca
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoApi.Models.Courses", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CName");

                    b.HasKey("CId");

                    b.ToTable("Courseses");

                    b.HasData(
                        new
                        {
                            CId = 1,
                            CName = "PHP"
                        },
                        new
                        {
                            CId = 2,
                            CName = "Java"
                        },
                        new
                        {
                            CId = 3,
                            CName = "C#"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Position");

                    b.HasKey("Id");

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Position = "Social Worker"
                        },
                        new
                        {
                            Id = 2,
                            Position = "Programmer II"
                        },
                        new
                        {
                            Id = 3,
                            Position = "Statistician I"
                        },
                        new
                        {
                            Id = 4,
                            Position = "Junior Executive"
                        },
                        new
                        {
                            Id = 5,
                            Position = "Mechanical Systems Engineer"
                        },
                        new
                        {
                            Id = 6,
                            Position = "Information Systems Manager"
                        },
                        new
                        {
                            Id = 7,
                            Position = "Account Executive"
                        },
                        new
                        {
                            Id = 8,
                            Position = "Biostatistician I"
                        },
                        new
                        {
                            Id = 9,
                            Position = "Recruiting Manager"
                        },
                        new
                        {
                            Id = 10,
                            Position = "Web Developer IV"
                        },
                        new
                        {
                            Id = 11,
                            Position = "Account Executive"
                        },
                        new
                        {
                            Id = 12,
                            Position = "Developer III"
                        },
                        new
                        {
                            Id = 13,
                            Position = "Nuclear Power Engineer"
                        },
                        new
                        {
                            Id = 14,
                            Position = "Junior Executive"
                        },
                        new
                        {
                            Id = 15,
                            Position = "Mechanical Systems Engineer"
                        },
                        new
                        {
                            Id = 16,
                            Position = "Senior Sales Associate"
                        },
                        new
                        {
                            Id = 17,
                            Position = "Legal Assistant"
                        },
                        new
                        {
                            Id = 18,
                            Position = "Biostatistician I"
                        },
                        new
                        {
                            Id = 19,
                            Position = "Biostatistician IV"
                        },
                        new
                        {
                            Id = 20,
                            Position = "Associate Professor"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Professors", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CId");

                    b.Property<string>("PName");

                    b.HasKey("PId");

                    b.HasIndex("CId");

                    b.ToTable("Professorses");

                    b.HasData(
                        new
                        {
                            PId = 1,
                            CId = 1,
                            PName = "Kasimir Cannon"
                        },
                        new
                        {
                            PId = 2,
                            CId = 2,
                            PName = "Ria Sims"
                        },
                        new
                        {
                            PId = 3,
                            CId = 3,
                            PName = "Regina Hess"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.StudentCourse", b =>
                {
                    b.Property<int>("SId");

                    b.Property<int>("CId");

                    b.HasKey("SId", "CId");

                    b.HasIndex("CId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            SId = 1,
                            CId = 2
                        },
                        new
                        {
                            SId = 2,
                            CId = 3
                        },
                        new
                        {
                            SId = 3,
                            CId = 1
                        },
                        new
                        {
                            SId = 4,
                            CId = 3
                        },
                        new
                        {
                            SId = 4,
                            CId = 2
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Students", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SName");

                    b.HasKey("SId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            SId = 1,
                            SName = "Zeus Randolph"
                        },
                        new
                        {
                            SId = 2,
                            SName = "Andrej Bojic"
                        },
                        new
                        {
                            SId = 3,
                            SName = "John Peters"
                        },
                        new
                        {
                            SId = 4,
                            SName = "John Doe"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("BirthPlace");

                    b.Property<string>("Email");

                    b.Property<int>("JobId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1979, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "South Sudan",
                            Email = "posuere.enim@porttitor.edu",
                            JobId = 14,
                            Name = "Kasimir Cannon"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1975, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Montserrat",
                            Email = "Vivamus.molestie@magna.co.uk",
                            JobId = 18,
                            Name = "Candace Velasquez"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1966, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Greece",
                            Email = "feugiat.tellus.lorem@etmagnisdis.co.uk",
                            JobId = 9,
                            Name = "Ria Sims"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1975, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Macao",
                            Email = "euismod.mauris@Aliquamvulputateullamcorper.com",
                            JobId = 20,
                            Name = "Regina Hess"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2010, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Bermuda",
                            Email = "mus@nonloremvitae.co.uk",
                            JobId = 11,
                            Name = "Renee Hobbs"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1985, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Comoros",
                            Email = "nec.ligula@anteiaculis.edu",
                            JobId = 20,
                            Name = "Carly Hicks"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2001, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Denmark",
                            Email = "amet.consectetuer.adipiscing@laoreet.net",
                            JobId = 18,
                            Name = "Zeus Randolph"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1992, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Congo, the Democratic Republic of the",
                            Email = "enim.nisl.elementum@Nullatemporaugue.com",
                            JobId = 6,
                            Name = "Lamar Gomez"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1971, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Spain",
                            Email = "mauris.sit@turpisegestasAliquam.org",
                            JobId = 14,
                            Name = "Lisandra Colon"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1966, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Guam",
                            Email = "vehicula.Pellentesque@maurisutmi.com",
                            JobId = 17,
                            Name = "Olympia Dunlap"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1980, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Dominica",
                            Email = "faucibus.leo.in@dapibusligula.org",
                            JobId = 14,
                            Name = "Alan Mosley"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1992, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Tanzania",
                            Email = "ridiculus@ligulaeu.net",
                            JobId = 15,
                            Name = "Destiny Humphrey"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1954, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Rwanda",
                            Email = "euismod@ornareFuscemollis.edu",
                            JobId = 4,
                            Name = "Berk Harrell"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1972, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Palestine, State of",
                            Email = "feugiat.Sed.nec@semNullainterdum.ca",
                            JobId = 6,
                            Name = "Maris Puckett"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2000, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Angola",
                            Email = "facilisi@eu.org",
                            JobId = 18,
                            Name = "Tanya Berg"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1995, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Chad",
                            Email = "quam.vel@arcu.co.uk",
                            JobId = 7,
                            Name = "Yardley Weeks"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2015, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "San Marino",
                            Email = "ante.bibendum@in.com",
                            JobId = 16,
                            Name = "Ebony Dickerson"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(1977, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Pakistan",
                            Email = "at.nisi@nullaante.ca",
                            JobId = 19,
                            Name = "Jayme Dalton"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1970, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Singapore",
                            Email = "gravida@Duisa.ca",
                            JobId = 8,
                            Name = "Teagan Barnett"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(2013, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Ecuador",
                            Email = "rutrum.eu@pharetraQuisque.org",
                            JobId = 12,
                            Name = "Macaulay Luna"
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(1977, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Kiribati",
                            Email = "porttitor@ornarelectus.com",
                            JobId = 18,
                            Name = "Hop Morrow"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1979, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Venezuela",
                            Email = "justo@dolorDonecfringilla.co.uk",
                            JobId = 15,
                            Name = "Darryl Clarke"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1963, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Solomon Islands",
                            Email = "porttitor.scelerisque@eu.org",
                            JobId = 20,
                            Name = "Herrod Gonzalez"
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(1994, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Sweden",
                            Email = "Maecenas@enimnonnisi.org",
                            JobId = 11,
                            Name = "Nita Britt"
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1989, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Norway",
                            Email = "mi@elit.edu",
                            JobId = 19,
                            Name = "Paula Morrison"
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(1996, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Congo (Brazzaville)",
                            Email = "ridiculus.mus.Proin@fermentumfermentum.com",
                            JobId = 10,
                            Name = "Nicole Farley"
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2006, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Namibia",
                            Email = "mollis@ategestas.edu",
                            JobId = 19,
                            Name = "Robert Fulton"
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(1992, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Peru",
                            Email = "magna@aneque.co.uk",
                            JobId = 6,
                            Name = "Noel Estrada"
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(1967, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Nigeria",
                            Email = "blandit.enim.consequat@acarcu.co.uk",
                            JobId = 2,
                            Name = "Yeo Contreras"
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(1967, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Heard Island and Mcdonald Islands",
                            Email = "nonummy.ac@lobortisrisus.co.uk",
                            JobId = 18,
                            Name = "Lacota Michael"
                        },
                        new
                        {
                            Id = 31,
                            BirthDate = new DateTime(1987, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Suriname",
                            Email = "at.arcu@nullaIntegerurna.ca",
                            JobId = 15,
                            Name = "Hasad Lamb"
                        },
                        new
                        {
                            Id = 32,
                            BirthDate = new DateTime(1982, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Peru",
                            Email = "posuere.cubilia.Curae@mifelisadipiscing.net",
                            JobId = 19,
                            Name = "Daryl Beasley"
                        },
                        new
                        {
                            Id = 33,
                            BirthDate = new DateTime(1958, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Ecuador",
                            Email = "mi@sollicitudincommodoipsum.net",
                            JobId = 12,
                            Name = "Kylee Johnston"
                        },
                        new
                        {
                            Id = 34,
                            BirthDate = new DateTime(2012, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Cambodia",
                            Email = "non.lacinia@augueSedmolestie.com",
                            JobId = 8,
                            Name = "Kennan Allison"
                        },
                        new
                        {
                            Id = 35,
                            BirthDate = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Guyana",
                            Email = "mauris@quam.ca",
                            JobId = 7,
                            Name = "Moses Henderson"
                        },
                        new
                        {
                            Id = 36,
                            BirthDate = new DateTime(1982, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Liechtenstein",
                            Email = "lacus.Ut@sed.co.uk",
                            JobId = 9,
                            Name = "Grace Hines"
                        },
                        new
                        {
                            Id = 37,
                            BirthDate = new DateTime(1998, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Nigeria",
                            Email = "ut.dolor@Nullaeuneque.com",
                            JobId = 1,
                            Name = "Scott Hall"
                        },
                        new
                        {
                            Id = 38,
                            BirthDate = new DateTime(1992, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Turkey",
                            Email = "non.justo@blanditviverraDonec.ca",
                            JobId = 16,
                            Name = "Omar Finch"
                        },
                        new
                        {
                            Id = 39,
                            BirthDate = new DateTime(1998, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Jamaica",
                            Email = "vestibulum.lorem.sit@Duissit.org",
                            JobId = 13,
                            Name = "Caesar Bowman"
                        },
                        new
                        {
                            Id = 40,
                            BirthDate = new DateTime(1972, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Ecuador",
                            Email = "egestas.ligula@sedest.edu",
                            JobId = 15,
                            Name = "Casey Peters"
                        },
                        new
                        {
                            Id = 41,
                            BirthDate = new DateTime(1997, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Azerbaijan",
                            Email = "libero@afelisullamcorper.edu",
                            JobId = 1,
                            Name = "Boris Sykes"
                        },
                        new
                        {
                            Id = 42,
                            BirthDate = new DateTime(2008, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "French Southern Territories",
                            Email = "Sed@molestie.org",
                            JobId = 19,
                            Name = "Erasmus Head"
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateTime(2003, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Madagascar",
                            Email = "ultricies.ligula.Nullam@nisi.edu",
                            JobId = 5,
                            Name = "Levi Sampson"
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateTime(1991, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Samoa",
                            Email = "eu.neque@semNulla.edu",
                            JobId = 4,
                            Name = "Colt Leonard"
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateTime(2002, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Falkland Islands",
                            Email = "elit.Curabitur.sed@nonlacinia.edu",
                            JobId = 7,
                            Name = "Tate Hutchinson"
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateTime(1969, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Guernsey",
                            Email = "vel.faucibus@non.net",
                            JobId = 14,
                            Name = "Elmo Mccarthy"
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateTime(1990, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Mali",
                            Email = "id.risus.quis@arcu.ca",
                            JobId = 15,
                            Name = "Violet Harding"
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateTime(2009, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Mali",
                            Email = "senectus.et.netus@quisdiam.co.uk",
                            JobId = 1,
                            Name = "Lani Richmond"
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateTime(2000, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Bouvet Island",
                            Email = "risus@ac.com",
                            JobId = 6,
                            Name = "Luke Glover"
                        },
                        new
                        {
                            Id = 50,
                            BirthDate = new DateTime(2001, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Gibraltar",
                            Email = "non.lobortis.quis@hendrerit.com",
                            JobId = 15,
                            Name = "Evangeline Wallace"
                        },
                        new
                        {
                            Id = 51,
                            BirthDate = new DateTime(2002, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Andorra",
                            Email = "non.enim.commodo@ac.ca",
                            JobId = 20,
                            Name = "Justin Reid"
                        },
                        new
                        {
                            Id = 52,
                            BirthDate = new DateTime(1995, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Latvia",
                            Email = "primis.in@eros.co.uk",
                            JobId = 13,
                            Name = "Nicholas Harvey"
                        },
                        new
                        {
                            Id = 53,
                            BirthDate = new DateTime(1983, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "C�te D'Ivoire (Ivory Coast)",
                            Email = "semper.pretium.neque@nequeInornare.ca",
                            JobId = 19,
                            Name = "Savannah Dotson"
                        },
                        new
                        {
                            Id = 54,
                            BirthDate = new DateTime(1987, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Sweden",
                            Email = "purus.in.molestie@Crasvulputatevelit.edu",
                            JobId = 5,
                            Name = "Avye Howard"
                        },
                        new
                        {
                            Id = 55,
                            BirthDate = new DateTime(1960, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Russian Federation",
                            Email = "luctus.ut.pellentesque@convallisdolorQuisque.com",
                            JobId = 10,
                            Name = "Mari Joyner"
                        },
                        new
                        {
                            Id = 56,
                            BirthDate = new DateTime(1966, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Vanuatu",
                            Email = "quam.dignissim.pharetra@Duisami.net",
                            JobId = 7,
                            Name = "Angela Wilder"
                        },
                        new
                        {
                            Id = 57,
                            BirthDate = new DateTime(1986, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Switzerland",
                            Email = "at.pretium.aliquet@ametnullaDonec.com",
                            JobId = 17,
                            Name = "Clayton Morales"
                        },
                        new
                        {
                            Id = 58,
                            BirthDate = new DateTime(1981, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Belarus",
                            Email = "Vestibulum.ante@Proinvel.net",
                            JobId = 13,
                            Name = "Yoshi Wilkins"
                        },
                        new
                        {
                            Id = 59,
                            BirthDate = new DateTime(1963, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Slovenia",
                            Email = "libero.dui@nisimagnased.co.uk",
                            JobId = 2,
                            Name = "Suki Buck"
                        },
                        new
                        {
                            Id = 60,
                            BirthDate = new DateTime(2012, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Hong Kong",
                            Email = "velit.Aliquam@feugiat.net",
                            JobId = 4,
                            Name = "Sheila Owen"
                        },
                        new
                        {
                            Id = 61,
                            BirthDate = new DateTime(1990, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Tonga",
                            Email = "eu.odio.Phasellus@enimnec.net",
                            JobId = 20,
                            Name = "Len Coleman"
                        },
                        new
                        {
                            Id = 62,
                            BirthDate = new DateTime(2002, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Niue",
                            Email = "vel@amet.com",
                            JobId = 4,
                            Name = "Tanisha Gallagher"
                        },
                        new
                        {
                            Id = 63,
                            BirthDate = new DateTime(1951, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Slovakia",
                            Email = "in.consequat@Mauris.net",
                            JobId = 16,
                            Name = "Urielle Puckett"
                        },
                        new
                        {
                            Id = 64,
                            BirthDate = new DateTime(1967, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Portugal",
                            Email = "turpis.egestas@Donec.org",
                            JobId = 8,
                            Name = "Nigel Peterson"
                        },
                        new
                        {
                            Id = 65,
                            BirthDate = new DateTime(2017, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Faroe Islands",
                            Email = "posuere.vulputate@tempus.com",
                            JobId = 2,
                            Name = "Honorato Torres"
                        },
                        new
                        {
                            Id = 66,
                            BirthDate = new DateTime(2009, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Martinique",
                            Email = "dictum@Aliquamfringilla.net",
                            JobId = 11,
                            Name = "Neil Thomas"
                        },
                        new
                        {
                            Id = 67,
                            BirthDate = new DateTime(1965, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Bahamas",
                            Email = "eget.venenatis.a@auctorvitaealiquet.ca",
                            JobId = 18,
                            Name = "Olga Bryant"
                        },
                        new
                        {
                            Id = 68,
                            BirthDate = new DateTime(2001, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Liberia",
                            Email = "vulputate@arcuSed.co.uk",
                            JobId = 16,
                            Name = "Tiger Hunt"
                        },
                        new
                        {
                            Id = 69,
                            BirthDate = new DateTime(1999, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Tokelau",
                            Email = "aliquet@sollicitudinadipiscing.com",
                            JobId = 11,
                            Name = "Gray Dalton"
                        },
                        new
                        {
                            Id = 70,
                            BirthDate = new DateTime(1956, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Chad",
                            Email = "vulputate.eu@Proin.net",
                            JobId = 12,
                            Name = "Davis Rowe"
                        },
                        new
                        {
                            Id = 71,
                            BirthDate = new DateTime(1961, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Liberia",
                            Email = "nibh.Phasellus.nulla@placerataugue.org",
                            JobId = 4,
                            Name = "Jenette Mcdowell"
                        },
                        new
                        {
                            Id = 72,
                            BirthDate = new DateTime(1952, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Morocco",
                            Email = "pharetra.sed@metusAeneansed.co.uk",
                            JobId = 13,
                            Name = "Ramona Lawrence"
                        },
                        new
                        {
                            Id = 73,
                            BirthDate = new DateTime(1982, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Korea, South",
                            Email = "amet@Inlorem.co.uk",
                            JobId = 9,
                            Name = "Emmanuel Garrett"
                        },
                        new
                        {
                            Id = 74,
                            BirthDate = new DateTime(2014, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Gambia",
                            Email = "accumsan@amifringilla.org",
                            JobId = 5,
                            Name = "Yasir Norris"
                        },
                        new
                        {
                            Id = 75,
                            BirthDate = new DateTime(2004, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Kiribati",
                            Email = "pellentesque.eget@auguemalesuada.net",
                            JobId = 12,
                            Name = "Sarah Brown"
                        },
                        new
                        {
                            Id = 76,
                            BirthDate = new DateTime(1960, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Greece",
                            Email = "ut@Nuncmaurissapien.com",
                            JobId = 19,
                            Name = "Juliet Miles"
                        },
                        new
                        {
                            Id = 77,
                            BirthDate = new DateTime(1952, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Lithuania",
                            Email = "vulputate.velit@urnaNullam.org",
                            JobId = 16,
                            Name = "Lance Holloway"
                        },
                        new
                        {
                            Id = 78,
                            BirthDate = new DateTime(1989, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "China",
                            Email = "risus@suscipitest.com",
                            JobId = 11,
                            Name = "Tanek Chaney"
                        },
                        new
                        {
                            Id = 79,
                            BirthDate = new DateTime(1964, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Cuba",
                            Email = "lobortis.mauris@sed.edu",
                            JobId = 11,
                            Name = "Clio Wagner"
                        },
                        new
                        {
                            Id = 80,
                            BirthDate = new DateTime(2019, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Cuba",
                            Email = "natoque.penatibus.et@gravidanunc.org",
                            JobId = 19,
                            Name = "Tanek Green"
                        },
                        new
                        {
                            Id = 81,
                            BirthDate = new DateTime(1954, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Zambia",
                            Email = "tortor@fringillacursuspurus.com",
                            JobId = 14,
                            Name = "Zeus Moore"
                        },
                        new
                        {
                            Id = 82,
                            BirthDate = new DateTime(1978, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Qatar",
                            Email = "blandit@egestasascelerisque.co.uk",
                            JobId = 9,
                            Name = "Reese Chambers"
                        },
                        new
                        {
                            Id = 83,
                            BirthDate = new DateTime(1975, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "�land Islands",
                            Email = "odio@necmollisvitae.com",
                            JobId = 13,
                            Name = "Hashim Swanson"
                        },
                        new
                        {
                            Id = 84,
                            BirthDate = new DateTime(1994, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Liechtenstein",
                            Email = "Donec.est@nonlaciniaat.edu",
                            JobId = 11,
                            Name = "Martin Stuart"
                        },
                        new
                        {
                            Id = 85,
                            BirthDate = new DateTime(1978, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Cocos (Keeling) Islands",
                            Email = "Nam.ac.nulla@disparturientmontes.edu",
                            JobId = 12,
                            Name = "Pearl Hebert"
                        },
                        new
                        {
                            Id = 86,
                            BirthDate = new DateTime(1997, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Argentina",
                            Email = "Sed.id@interdumliberodui.net",
                            JobId = 17,
                            Name = "Hillary Shepard"
                        },
                        new
                        {
                            Id = 87,
                            BirthDate = new DateTime(1955, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Australia",
                            Email = "faucibus.leo@ac.co.uk",
                            JobId = 9,
                            Name = "Adria Kerr"
                        },
                        new
                        {
                            Id = 88,
                            BirthDate = new DateTime(1987, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Liechtenstein",
                            Email = "nibh.Quisque.nonummy@FuscemollisDuis.edu",
                            JobId = 12,
                            Name = "Melodie Blevins"
                        },
                        new
                        {
                            Id = 89,
                            BirthDate = new DateTime(1956, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Sierra Leone",
                            Email = "Mauris.non@consequatpurus.net",
                            JobId = 15,
                            Name = "Lyle Wise"
                        },
                        new
                        {
                            Id = 90,
                            BirthDate = new DateTime(2017, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Cook Islands",
                            Email = "magna.nec.quam@aclibero.edu",
                            JobId = 10,
                            Name = "Keefe Stewart"
                        },
                        new
                        {
                            Id = 91,
                            BirthDate = new DateTime(1976, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Dominican Republic",
                            Email = "vel.venenatis@disparturientmontes.org",
                            JobId = 19,
                            Name = "Gloria York"
                        },
                        new
                        {
                            Id = 92,
                            BirthDate = new DateTime(1954, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Mali",
                            Email = "ipsum.dolor.sit@neceleifendnon.edu",
                            JobId = 14,
                            Name = "Boris Hutchinson"
                        },
                        new
                        {
                            Id = 93,
                            BirthDate = new DateTime(1978, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Albania",
                            Email = "rutrum@arcuSedeu.ca",
                            JobId = 14,
                            Name = "James Knapp"
                        },
                        new
                        {
                            Id = 94,
                            BirthDate = new DateTime(2000, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Macedonia",
                            Email = "lacinia.vitae@risus.org",
                            JobId = 10,
                            Name = "Leah Gonzalez"
                        },
                        new
                        {
                            Id = 95,
                            BirthDate = new DateTime(2015, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Qatar",
                            Email = "dolor.Nulla.semper@tortorNunc.co.uk",
                            JobId = 10,
                            Name = "Abbot Dean"
                        },
                        new
                        {
                            Id = 96,
                            BirthDate = new DateTime(2004, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Pakistan",
                            Email = "tellus.lorem.eu@lobortisquama.co.uk",
                            JobId = 10,
                            Name = "Xenos Bean"
                        },
                        new
                        {
                            Id = 97,
                            BirthDate = new DateTime(1998, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Samoa",
                            Email = "elementum.sem.vitae@Pellentesquehabitantmorbi.co.uk",
                            JobId = 18,
                            Name = "Keiko Hoover"
                        },
                        new
                        {
                            Id = 98,
                            BirthDate = new DateTime(2006, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Kazakhstan",
                            Email = "tellus.eu.augue@Aeneanegestas.com",
                            JobId = 20,
                            Name = "Cassidy Kerr"
                        },
                        new
                        {
                            Id = 99,
                            BirthDate = new DateTime(2020, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Honduras",
                            Email = "sit.amet@interdum.edu",
                            JobId = 8,
                            Name = "Haley Gilbert"
                        },
                        new
                        {
                            Id = 100,
                            BirthDate = new DateTime(2006, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlace = "Slovakia",
                            Email = "semper.auctor@adipiscinglacus.org",
                            JobId = 5,
                            Name = "Price Mcleod"
                        });
                });

            modelBuilder.Entity("TodoApi.Models.Professors", b =>
                {
                    b.HasOne("TodoApi.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TodoApi.Models.StudentCourse", b =>
                {
                    b.HasOne("TodoApi.Models.Courses", "Course")
                        .WithMany()
                        .HasForeignKey("CId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TodoApi.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("SId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TodoApi.Models.User", b =>
                {
                    b.HasOne("TodoApi.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
